language: python
python:
    - "3.8"

services:
    - docker

before_script: 
    - pip install docker-compose
   
script:
    - docker-compose build
    - docker-compose run player-comparison-service sh -c "python test_endpoints.py"
    - docker-compose run frontend sh -c "python test_microservice_endpoints.py"
