language: python
python:
    - "3.8"

services:
    - docker

before_script: 
    - pip install docker-compose
   
script:
    - docker-compose build
    # Tests fails because config variables for db queries are not included in git repo, they work locally.
    #- docker-compose run general-service sh -c "python3 -m unittest"
    #- docker-compose run player-comparison-service sh -c "python3 -m unittest"


    