language: python
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose build
    - cd frontend-service && venv source/bin/activate && python test_microservice_endpoints.py && deactivate && cd ..
    - cd general-service && venv source/bin/activate && python test_endpoints.py && deactivate && cd ..
    - cd player-comparison-service && venv source/bin/activate && python test_endpoints.py && deactivate && cd ..
