language: python
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose build
    - cd frontend-service && python test_microservice_endpoints.py && cd ..
    - cd general-service && python test_endpoints.py && cd ..
    - cd player-comparison-service && python test_endpoints.py && cd ..
