language: python
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose up
    - docker exec -it xstat_general-service_1 /bin/bash && python test_endpoints.py && exit
