version: '3'

services: 
    frontend:
        build: ./frontend-service
        volumes:
            - ./frontend-service:/usr/src/app
        ports:
            - 5000:80
        depends_on: 
            - general-service
            - player-comparison-service
        restart: always

    general-service:
        build: ./general-service
        volumes:
            - ./general-service:/usr/src/app
        expose:
            - "80"
        restart: always

    player-comparison-service:
        build: ./player-comparison-service
        volumes:
            - ./player-comparison-service:/usr/src/app
        expose:
            - "80"
        restart: always
        

            