version: '3'

services: 
    frontend:
        build: ./frontend-service
        volumes:
            - ./frontend-service:/app
        ports:
            - 8080:8080 # Left = HOST. Right = CONTAINER
        depends_on: 
            - general-service
            - player-comparison-service
        restart: always

    general-service:
        build: ./general-service
        volumes:
            - ./general-service:/usr/src/app
        ports:
            - 8081:80
        restart: always

    player-comparison-service:
        build: ./player-comparison-service
        volumes:
            - ./player-comparison-service:/usr/src/app
        ports:
            - 8082:80
        restart: always

    monitor-service:
        build: ./monitor-service
        volumes: 
            - ./monitor-service:/usr/src/app
        ports:
            - 8083:5000
        restart: always
        

            